version: '3.7'

services:
  s-asl:
    container_name: c-asl
    build: 
      context: . 
    image: asl:1.0.0
    restart: unless-stopped
    networks:
      n-mkn: {}
    labels:
      - traefik.enable=true
      - traefik.http.routers.r-asl.entrypoints=e-secure
      - traefik.http.routers.r-asl.rule=Host(`aslog.co.id`)
      - traefik.http.routers.r-asl.tls=true
      - traefik.http.routers.r-asl.tls.certResolver=lets-encrypt

networks:
  n-mkn:
    external: true
    name: n-mkn
